### ISSUE TITLE
YAML Multiline Strings

### ISSUE THREAD

**Issue by Infrid** [bartosz-antosik/vscode-spellright#235]
thanks for your extension, I would like to report a bug and/or a feature request.

When I am editing YAML files I use multilne strings a lot, unfortunately spellright cannot do its job all the time, here an example

```yaml
# this is a comment, we could write anything from note to explanaitions

# yoyo how bad coul spel?

some_level:
  type: radiogata
  something: "radiogata"

  # the yaml spec is preatty neat, it can handle verbatim text quite easly

  # we are going to keep the newlines
  layers: |
    ciao ciaoc 
    iwewo oo3owo3

    oro pane cioc

  layer2: |
  " double quoted txt wer
  wer are going to write someting wrong"

  layer3: |
  ' this is a single quot e
  another line another sotry '
```

what I see in vscode

![image](https://user-images.githubusercontent.com/3205312/50000171-9aa9e880-ff90-11e8-834d-7fa62b3891e6.png)

what I expect

![image](https://user-images.githubusercontent.com/3205312/50000257-e3fa3800-ff90-11e8-93c3-2c8271c55de4.png)

multiline strings in yaml are a bit clumsy, [here an useful resource on that](https://yaml-multiline.info/). I tried to play with settings but I wasn't able to make the plugin work as I expect. 

Is this a bug? a missing feature? 

Thanks!
